### ISSUE TITLE
Modpack crash

### ISSUE THREAD

**Issue by Taknax** [someaddons/performant_issues#229] opened 2022-02-19 20:35 UTC
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

My modpack crashes, but before the crash it is running perfect. I got a high performance grant.

**To Reproduce**
1. Dont try to reproduce. The crash is on a modpack with 200+ mods.

**Expected behavior**

I profit from the performance, if i can fix the issues, i would like to use in my modpack.

I saw much entries in the latest.log: "[main/ERROR] [com.performant.coremod.Performant/]: Bad loottable added: net.minecraft.loot.LootPool@4ac68478, name is null". What could cause this?

**Screenshots**

** Mod version **
Your mods version: 1.16.2-5-3.87m

** Logs **
Latest/Crash log
[crash-2022-02-19_21.08.05-server.txt](https://github.com/someaddons/performant_issues/files/8102957/crash-2022-02-19_21.08.05-server.txt)
[latest.log](https://github.com/someaddons/performant_issues/files/8102958/latest.log)

**Comment by someaddons** [comment] 2022-02-19 20:39
its an issue with the collective/serilum mod, probably called villagename or so

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 188.60 seconds (should be max 0.05)
	at com.natamus.collective.functions.EntityFunctions.getEntityString(EntityFunctions.java:70) ~[?:4.7] {re:classloading}
	at com.natamus.collective.functions.EntityFunctions.isModdedVillager(EntityFunctions.java:48) ~[?:4.7] {re:classloading}
	at com.natamus.villagernames.events.VillagerEvent.onSpawn(VillagerEvent.java:33) ~[?:1.0] {re:classloading}

```

"Bad loottable added:" is caused by mods adding a loottable without specifying a name. Closing since neither is an issue caused by performant

**Closed by someaddons** 2022-02-19 20:39 UTC

**Comment by Taknax** [comment] 2022-02-19 21:21
Could i ignore the issues? Looks like i have much more mods in my modpack have the same issue.

**Comment by someaddons** [comment] 2022-02-19 21:23
ye the issues you can ignore, its just a warning so those mods fix it someday maybe
