### ISSUE TITLE
Crash: Performant and Pattern Terminal from AE2

### ISSUE THREAD

**Issue by ProOrange** [someaddons/performant_issues#128] opened 2021-04-06 15:18 UTC
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
I'm using TNP Limitless 3 modpack. Seems like Performant caused game crashes when i openning AE2 pattern treminal. After removing Performant from modpack crash is gone.

**To Reproduce**
    1. Setup base AE2 network with 6-10 filled with items storage cells
    2. Place Pattern Terminal
    3. Fill player inventory with different items
    4. Open pattern terminal
    5. Sometimes app will crash, sometimes just lag for 3-30 seconds

**Expected behavior**
Without performant openning take around 1-2 seconds.

** Mod version **
5-3.40m

** Logs **
No crash log since game isn't directly crashed, looks like it goes into infinite calculation loop (but still no SO)

**Comment by someaddons** [comment] 2021-05-24 11:14
cant reproduce, probably fixed in the newest

**Closed by someaddons** 2021-05-24 11:14 UTC
