### ISSUE TITLE
[1.15.2] Crashing and skeletons shooting without looking/'aiming' at me 

### ISSUE THREAD

**Issue by elienaimg** [someaddons/performant_issues#33] opened 2020-11-06 18:05 UTC
**Describe the bug**
Crashing 'explained' with timestamps  on logs and also the skeletons are behaving oddly. they don't look at me while attacking. they 'aim' the first time they fire at me but that's it.. (screenshots made with this mod alone)

![2020-11-06_15 13 50](https://user-images.githubusercontent.com/71791383/98398887-6afea080-2040-11eb-80b0-6dda765750d2.png)
![2020-11-06_15 13 59](https://user-images.githubusercontent.com/71791383/98398907-718d1800-2040-11eb-8431-5cffe5df94e3.png)
![2020-11-06_15 13 52](https://user-images.githubusercontent.com/71791383/98399455-26bfd000-2041-11eb-8560-cc591bd23787.png)

 

**To Reproduce**
Install mod

**Expected behavior**
--

**Screenshots**
Attached

** Mod version **
performant-1.15-3.11m.jar

Crash logs:
https://gist.github.com/elienaimg/3401071cdf0ffc39fbc882ddfba62361
https://gist.github.com/elienaimg/bcc84430c818f7371728e28f5a25edc0

Latest/Crash log
https://gist.github.com/elienaimg/02638c0a867aa9d130262d14c40696ac

**Comment by elienaimg** [comment] 2020-11-06 20:12
I've used the config to forbit the (minecraft:salmon) mob related to the crashes for now... have no idea how to deal with the skeleton though..

**Comment by PantsWP** [comment] 2020-11-07 06:55
On our Valhelsia 2 server, we don't receive the Salmon crashes, well, not anymore.

However, for the first time, it crashed due to a skeleton trying to pathfind, as can be seen here:
https://pastebin.com/LPBGgpNZ

A similar issue was reported on the Mojang issue bug tracker for Minecraft 1.11.2 and it was caused by the game trying to send pathfinding tasks too quickly. It has since been resolved: https://bugs.mojang.com/browse/MC-117839

**Comment by elienaimg** [comment] 2020-11-07 12:57
You could make a trial and error gameplay so to say...  
Try setting to false this config and see if it still crashes:
	fastPathFinding = true
if it happens again you can try and see if disabling  some of the ["Entity settings"] fixes your problem...

**Comment by elienaimg** [comment] 2020-11-07 13:05
> I've used the config to forbit from spawning the (minecraft:salmon) mob related to the crashes for now... have no idea how to deal with the skeleton though..


multiEntities = true 	 -  was the feature disabling the hability of the skeletons to look at me. 
I tested in creative and they look at me for 4,5 seconds and then blankly stares at something.

**Comment by someaddons** [comment] 2020-11-10 18:52
should be fixed in v3.12m

**Closed by someaddons** 2020-11-10 18:52 UTC
