### ISSUE TITLE
Villager Pathfinding Problems

### ISSUE THREAD

**Issue by baronjutter** [someaddons/performant_issues#91] opened 2021-01-14 01:07 UTC
Enjoying the server performance boost for this on our brand new 1.16.4 forge server.  Yes, sometimes entities take a couple extra seconds to react but that's a small price to pay for the performance.  What I'm having big troubles with are villagers. I've worked a ton with the odd pathfinding abilities of villagers extensively, but with performant they seem to have become significantly dumber.  They will often get stuck on a single block they could easily jump over but refuse, acting like it isn't there.  They'll walk around objects no longer present.  They'll refuse to path around walls or make even the most simple of detours.  And this is all after letting them re-adjust to any changes to their surroundings for over an hour.  Other mobs don't have this problem, the golems protecting the village don't have this problem, only the villagers them selves.  

It's very inconsistent too.  I'll remove a bunch of villager beds and place them somewhere new.  Maybe 2/3 of the villagers will quickly adapt to the new location and path, the others though will try to path to where the beds were then jump/spin endlessly every night, night after night.

It almost feels like something is preventing villagers from sometimes updating their pathing, that they're added to the processing queue for this task but it never gets done.

**Comment by someaddons** [comment] 2021-03-21 17:50
can't seem to reproduce the issues

**Comment by MarioSMB** [comment] 2021-04-04 16:42
My guess is this would be caused by the disableNotifyOnBlockChange setting - I too have been seeing villagers attempt to jump over blocks that were recently removed and such.

**Comment by someaddons** [comment] 2021-04-20 20:53
should be fixed

**Closed by someaddons** 2021-04-20 20:53 UTC
