### ISSUE TITLE
in .26, enemies do not get damaged most of the time when you attack them with Better Hurt Timer installed

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/performant_issues#71] opened 2021-01-01 21:02 UTC
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**
1. launch world with performant and BHT
2. attack an enemy
3. notice how most of the hits dont land

**Expected behavior**
to attack enemy

** Mod version **
3.26m
https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer

**Comment by BugmanBugman** [comment] 2021-01-01 21:10
This seems to only happen in conjunction with the Better Hurt Timer mod

**Comment by someaddons** [comment] 2021-01-06 13:17
might be fixed with version 3.27m at least I can't reproduce it

**Comment by BugmanBugman** [comment] 2021-01-07 21:13
Seems to be happening like the other issue, because of the https://www.curseforge.com/minecraft/mc-mods/modern-ui mod

**Comment by someaddons** [comment] 2021-01-07 22:33
so it works without the ui mod? sounds weird

**Comment by BugmanBugman** [comment] 2021-01-07 23:28
Yea, it is pretty odd, I singled it down to those mods. I reported to them as well

Sent from my iPhone

On Jan 7, 2021, at 4:34 PM, someaddons <notifications@github.com> wrote:

﻿

so it works without the ui mod? sounds weird

**Comment by BloCamLimb** [comment] 2021-01-08 04:03
It's weird. I tested removing all server logic codes and the network channel, it still makes Mekanism pipes and Refined Storage stop working, with both Performant and Modern UI installed.

**Comment by someaddons** [comment] 2021-01-09 16:15
found out what caused it, its because modernUI uses a forge bus creator very early, shifting up all normal forge bus ID's. Fixed in performant 3.30m

**Closed by someaddons** 2021-01-09 16:15 UTC
