### ISSUE TITLE
Performant mod affecting mowzie mobs

### ISSUE THREAD

**Issue by GauntAndreX8** [someaddons/performant_issues#169] opened 2021-07-14 23:49 UTC
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**

**To Reproduce**

**Expected behavior**
the barakoya seems to have an animation error they keep flickering do you think you can fix this plz
i asked mowzie and said that this mod is the reason why this glitch occur you think you can fix it

**Screenshots**

** Mod version **
1.16.2-5-3.70m.jar

** Logs **
Latest/Crash log

**Comment by someaddons** [comment] 2021-07-15 10:29
I'm unable to reproduce anything like that, so will need more info:

1. Which mods are you using and their exact versions
2. Which exact steps are you using to reproduce the issue
3. Screenshot/video showing the issue

**Comment by GauntAndreX8** [comment] 2021-07-15 19:54
1. Mowzie mobs-1.5.19 and performant 1.16.2-5-3.70m.jar in minecraft 1.16.5
2.  what i'm saying is that the ai change from this mod is affecting the other mob from another mod that is not suppose to do
when i remove the mod they work as they were suppose to do
3.  here is an example video what i mean

https://user-images.githubusercontent.com/85809443/125849111-b2d68096-b30a-44a9-903d-d36f1aba32a1.mp4

**Comment by someaddons** [comment] 2021-07-16 08:01
well performant does not have any "AI change" mechanic, so it can't possibly that. But I'll look into what might affect their behaviour

**Comment by GauntAndreX8** [comment] 2021-07-16 20:14
Oh ok thxs

**Comment by GauntAndreX8** [comment] 2021-07-17 23:20
Sry if I sound like I’m rushing you but is the fix ready yet?

**Comment by someaddons** [comment] 2021-07-18 20:29
you do realize that modding is a completly unpaid free-time activity, just like you playing the game? :D

**Comment by GauntAndreX8** [comment] 2021-07-19 00:10
Oh ok I’ll wait then

**Comment by MrJorman** [comment] 2021-08-03 14:49
+ too problem.

**Comment by GauntAndreX8** [comment] 2021-08-03 15:23
What you mean

**Comment by GauntAndreX8** [comment] 2021-10-09 21:49
Sry I’m asking this again but the bug is still here I downloaded the latest one and still exists

**Comment by someaddons** [comment] 2021-11-05 17:18
I've debugged the issue and its caused by mowzies mobs probably uninentionally resetting the target and thus causing the healing AI to stop, at this point in code below:
In `LivingUpdateEvent`:
![image](https://user-images.githubusercontent.com/38401808/140551541-b9a493a3-f685-4e19-8047-04d2eb5093c9.png)

The bug is only visually noticeable with performant because it only starts goals again after 4 ticks as opposed to vanilla every one ticks. You can work around the visuals by setting the config option `goalSelectorTickRate` to 1, but I'm sure mowzies would like to fix their underlying code here anyways.

Closing since not actually a performant issue

**Closed by someaddons** 2021-11-05 17:18 UTC
