### ISSUE TITLE
Mob spawning down to almost nothing

### ISSUE THREAD

**Issue by hvdklauw** [someaddons/performant_issues#65] opened 2020-12-28 15:07 UTC
Hardly any mobs spawning, even on hard.

Default config is used and when I removed performant and logged back in I got instantly killed by all the mobs around me.

**To Reproduce**
1. Download Enigmatica 6 version 0.3.2
2. Add performant
3. Go to the nether and find a fortress
4. Hardly any mobs (blaze from spawners)

**Expected behavior**
A lot of mobs, especially wither skeletons

** Mod version **
performant-1.16.2-4-3.24m.jar

**Comment by Amosh73** [comment] 2020-12-28 15:46
I second that. Made my own modpack from scratch to expand on my Vanilla world.

Have an Enderman Farm in the End, far away from the main island. Works like a charm without this mod, but as soon as perfomant is added, next to nothing spawns. The main island is almost deserted.

I tried switching off several features in the mod's config file, but none of them helped.

performant-1.16.2-4-3.25m.jar on the newest forge version 1.16.4-35.1.13

**Comment by BugmanBugman** [comment] 2020-12-28 21:32
Hostile mob spawning seems to be restricted for me too

**Comment by willrun4fun** [comment] 2020-12-29 20:23
Same here.

**Comment by someaddons** [comment] 2020-12-29 23:52
performant slows down mob spawns intervals, so it does take longer to spawn the amount of mobs. But testing it against vanilla it does end up at the same amount of mob spawns. I guess you mostly noticed it with mob spawner builds slowing down a bunch.
`/execute if entity @e` gives you a full entity count. You can turn up the max amount of entities with the config setting mob density

**Comment by bricktsre** [comment] 2020-12-30 18:12
The problem is the time it takes to get to the same number of mobs. My server made an end farm 200 blocks away from the main island. With performant running default no enderman were spanning at the farm. Turning the mod off immediately rectified that. I was able to approach vanilla spawn rates by turning fastSpawnRadius and fastChunkBlocks off and increasing entitydensity to 5. In our testing literally nothing would spawn off the main end island even when the far away chunks were the only ones loaded.

**Comment by someaddons** [comment] 2020-12-30 23:30
ye I'll increase the default rate at which it spawns and add a config for it

**Comment by someaddons** [comment] 2020-12-31 13:49
fixed in 3.26m

**Closed by someaddons** 2020-12-31 13:49 UTC
